name: Update submodules on repository_dispatch

on:
  repository_dispatch:
    types: [ sync-shared-submodules ]

env:
  COMMIT_MESSAGE: "chore: update submodules"

jobs:
  sync-shared-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          submodules: "true"
      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
